### ISSUE TITLE
Panel icon pixelation

### ISSUE THREAD

**Issue by hughwilliams94** [Doron-Behar/insync.aur#1]
When running in KDE the panel indicator icon is pixelated. Having just come from Kubuntu I can confirm this was not an issue there, in Plasma 5.7.5

**Comment by Doron-Behar** [comment]
Hello there :)
I forked this repo from the [AUR](https://aur.archlinux.org/packages/insync) page so I could just share a little tweak I wanted to suggest the original maintainer of the original repo. Try post a thread in [insync's forum](forums.insynchq.com), It's pretty good and they usually help you solve problems like that there.
